<a href="https://colab.research.google.com/github/Shreya693/Shreya693/blob/main/DL_Dimension_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
one_d = torch.arange(1,10) # arange() initilizes a 1D tensor
one_d

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
two_d = one_d.view(3,3)
two_d

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
two_d.dim() # returns the dimension of tensor --> a 2D matrix with 3x3 rows and columns

2

In [6]:
# fetch elements from matrix
two_d[0,2] # first row(0th index) and 3rd column(2nd index)

tensor(3)

In [7]:
# 3D tensor
x = torch.arange(18).view(2,3,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [8]:
# SLICING 3D Tensors
x[0,1,1]

tensor(4)

In [9]:
x[1,:,:]

tensor([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

In [11]:
# Matrix multiplication
mat_a = torch.tensor([0,3,5,5,5,2]).view(2,3)
mat_a

tensor([[0, 3, 5],
        [5, 5, 2]])

In [12]:
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [14]:
# matrix multiplication --> torch.matmul()

torch.matmul(mat_a,mat_b)

mat_a @ mat_b # another way to do matrix mul

tensor([[ 29, -16],
        [ 38,   6]])

In [16]:
# Derivatives

'''
If you make a tensor with:
 "requires_grad=True"

PyTorch will track all operations on that tensor.

Later, you can call:
"y.backward()"

and PyTorch will automatically compute dy/dx.
'''

'\nIf you make a tensor with:\n "requires_grad=True"\n\nPyTorch will track all operations on that tensor.\n\nLater, you can call:\n"y.backward()"\n\nand PyTorch will automatically compute dy/dx.\n'

In [19]:
x = torch.tensor(2.0, requires_grad = True)
y = 9 * x ** 4 + 2 * x ** 3 + 3 * x ** 2 + 6 * x + 6
y.backward()
x.grad

tensor(330.)

In [22]:
# Partial derivatives
x = torch.tensor(1.0, requires_grad = True)
z = torch.tensor(2.0, requires_grad = True)
y = x ** 2 + z ** 3
y.backward()
print(x.grad)
print(z.grad)

tensor(2.)
tensor(12.)
